

env:
  THRESHOLD_OF_IMAGE_PRC: 3
  THRESHOLD_OF_TXTBOXES_LENGTH: 0
  THRESHOLD_OF_TXT_PRC: 5
  MIN_NUMBER_OF_DATA_TABLE_LINES: 4
  IMG_HANDLER_CREATION_TASKS_BUFFER: 5
  GET_PAYLOADS_BUFFER: 5
  MAX_H_OF_WORD: 40
  MIN_H_OF_WORD: 5
  MIN_W_OF_WORD: 20
